### ISSUE TITLE
pypi wanted?

### ISSUE THREAD

**Issue by michaelaye** [cmillion/pds-util#2]
i'm pretty good at creating a pypi package by now, do you want your pds-util to be available on pypi? I could do that, and then we could get this code ready for applying to be a planetarypy member if you want, get's you more eyes on the code and more users. and then we can figure out how to enter it to a planetarypy core package later?

**Comment by cmillion** [comment]
Thank you for the encouragement. Let me try to find time in the next few weeks to clean up what I have (not all of which has been pushed to Github) into a minimum viable package for pushing to pypi. It will break on a lot of PDS3 data, especially much older data, but it will also work for a lot of existing data, and will be a more complete solution than anything else that currently exists for Python.

**Comment by cmillion** [comment]
The repo for the (under development) "universal PDS reader tool" is now [MillionConcepts/pdr](https://github.com/MillionConcepts/pdr). This repo will be retained for other PDS data related utility / dev work, and hosting of some instructional notebooks.

**Comment by michaelaye** [comment]
you kinda didn't say if you want me to do the packaging for you or if you want to do it on your own or if you rather still continue to develop without a pypi package first?

**Comment by cmillion** [comment]
I would rather develop a little more without a pypi package and then I would like your help packaging. I've done it before, but it's been a while.
